collision_monitor:
  ros__parameters:
    use_sim_time: false
    base_frame_id: "base_footprint"
    odom_frame_id: "odom"
    cmd_vel_in_topic: "diff_drive_controller/cmd_vel_unstamped"         # Topic vận tốc đầu vào (từ Nav2/Teleop)
    cmd_vel_out_topic: "diff_drive_controller/cmd_vel_unstamped"        # Topic vận tốc đầu ra (gửi tới motor driver)
    state_topic: "collision_monitor_state"
    transform_tolerance: 0.2
    source_timeout: 2.0
    base_shift_correction: true
    stop_pub_timeout: 2.0

    # Khai báo các nguồn dữ liệu cảm biến
    observation_sources: ["scan"]

    scan:
      type: "scan"
      topic: "/scan_filtered"
      enabled: true

    # Khai báo danh sách các vùng bảo vệ (Được ưu tiên theo thứ tự từ trên xuống dưới)
    polygons: ["PolygonStop", "PolygonSlow"]

    # Stop Zone
    PolygonStop:
      type: "polygon"
      points: [0.4, 0.3,  0.4, -0.3,  -0.4, -0.3,  -0.4, 0.3]
      action_type: "stop"
      max_points: 3             # lon hon 3 diem cam bien trong vung robot dung lai
      visualize: true
      polygon_pub_topic: "polygon_stop"

    # Slowdown Zone
    PolygonSlow:
      type: "polygon"
      points: [0.8, 0.5,  0.8, -0.5,  -0.8, -0.5,  -0.8, 0.5]
      action_type: "slowdown"
      slowdown_ratio: 0.3       
      max_points: 3
      visualize: true
      polygon_pub_topic: "polygon_slow"