laser_filter:             # phai dat trung ten voi name trong launch file cua laser_filter_node (phai git clone pkg laser_filter ve nua)
  ros__parameters:
    filter1:              # phai ten la filter1 (danh so thu tu)
      name: angle_filter
      type: laser_filters/LaserScanAngularBoundsFilterInPlace         #laser_filters/LaserScanAngularBoundsFilter 
      params:
        lower_angle: 0.0
        upper_angle: 3.14159 

